name: ASTDiff Bot

on:
  issue_comment:
    types: [created]

jobs:
  diff:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Step 0: Check for @diff trigger and get the URL command
      - name: Check for @diff trigger
        id: check_diff
        uses: actions/github-script@v6
        with:
          script: |
            const commentBody = context.payload.comment.body;
            const regex = /@diff\s+(\S+)/;  // Match the next non-whitespace string after @diff
            const match = commentBody.match(regex);

            if (match) {
              core.setOutput('triggered', 'true');
              core.setOutput('url', match[1].trim());  // Capture the URL-like string
            } else {
              core.setOutput('triggered', 'false');
            }
    
      # Step 1: Run RefactoringMiner Docker image
      - name: Run RefactoringMiner Docker image
        if: ${{ steps.check_diff.outputs.triggered == 'true' }}
        run: |
          # Pull the Docker image and run it with port forwarding
          docker pull tsantalis/refactoringminer
          docker run -d --env OAuthToken=${{ secrets.OAUTHTOKEN }} -p 6789:6789 tsantalis/refactoringminer diff --url "${{ steps.check_diff.outputs.url }}" 
    
      # Step 2: Install ngrok
      - name: Install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
          | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
          | sudo tee /etc/apt/sources.list.d/ngrok.list \
          && sudo apt update \
          && sudo apt install ngrok

      # Step 3: Authenticate ngrok
      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK }}

      # Step 4: Expose Docker container via ngrok
      - name: Expose Docker container via ngrok
        id: expose_ngrok
        if: ${{ steps.check_diff.outputs.triggered == 'true' }}
        run: ngrok http 6789 &

      # Step 5: Retrieve ngrok URL and store it as an output
      - name: Get ngrok URL
        id: get_ngrok_url
        run: |
          # Retrieve the ngrok URL
          ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok_url=$ngrok_url" >> $GITHUB_ENV
          echo "ngrok_url=$ngrok_url"

      # Step 6: Reply with the ngrok URL
      - name: Reply with ngrok URL
        if: ${{ steps.check_diff.outputs.triggered == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.check_diff.outputs.url }}';
            const ngrok_url = '${{ env.ngrok_url }}"';
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 You triggered the bot with the URL: \`${url}\`. The diff is being processed at: ${ngrok_url}`
            })
            
      # Step 7: Keep the container alive for 10 more minutes
      - name: Keep container alive
        run: sleep 600
